### ISSUE TITLE
Esc key not working

### ISSUE THREAD

**Issue by mclarkson** [gemian/xkeyboard-config#1]
Esc key does not work for me maybe due to commit 71bb1e8e956184da077b5a1bc387f23fdb3ab253.

$ uname -a
Linux localhost 3.18.41+ #59 SMP PREEMPT Wed Mar 7 19:41:32 MSK 2018 aarch64 GNU/Linux

Do I need to upgrade my kernel?

**Comment by adamboardman** [comment]
Yes see: https://github.com/gemian/gemini-keyboard-apps/wiki/DebianTP#update-the-kernel

**Comment by mclarkson** [comment]
I already followed that documentation. It shows the same version of kernel I have so I did not upgrade.
Is the kernel version listed there correct?
What kernel version should I be using?

**Comment by adamboardman** [comment]
The documentation there says - Mar 26, you claimed Mar 7, that to my mind is different?

Remember date is more reliable than version number due to version numbers being reset depending on who built the kernel/last time they cleared out their build tree.

**Comment by mclarkson** [comment]
Thanks, I did not realise, although I do remember it being mentioned somewhere. I have linux as the default boot option so NOTE says I need to use the flashing tool. Do you know if I am able to flash just the kernel? Any instructions you know of?

**Comment by adamboardman** [comment]
Yes if you've got the latest flash tool then just swap in the new kernel and pick download only and then only tick the one 'boot' partition. (if you've put linux as default then the linux_boot partition is actually now your android kernel).

**Comment by mclarkson** [comment]
Worked perfectly. Thanks!
As an added bonus the system now sleeps as soon as I close the lid, which is great!
