### ISSUE TITLE
Add slovak keyboard map

### ISSUE THREAD

**Issue by okruhliak** [gemian/xkeyboard-config#4]
Hallo,
I am new here. I am owner Gemini PDA with EN(US) keyboard layout. I would like include slovak keyboard layout into Debian (Gemini). If it is possible, I  attached one. It is derived from Czech (CZ), the changes are: ľ, ť, ô, ä.

Thank you
Ladislav
P.S.
I am not a programmer :(
[xkb_map_sk.txt](https://github.com/gemian/xkeyboard-config/files/2890109/xkb_map_sk.txt)

**Comment by adamboardman** [comment]
Added, thanks for the contribution. Code looked fine...

**Comment by okruhliak** [comment]
Hello Adam,
thank you for quick adding slovak layout.
I made one error, sorry, Fn+P is in one groupe ncaron "ň", but right is adiaeresis "ä". Change it, please.
Ladislav
Edit 1
I found next one error in config, parenleft was there two times, but parenright no one. It is repaired.
[xkb_map_sk_20190222-1.txt](https://github.com/gemian/xkeyboard-config/files/2896217/xkb_map_sk_20190222-1.txt)
