### ISSUE TITLE
Swiss keymap is missing

### ISSUE THREAD

**Issue by sschueller** [gemian/xkeyboard-config#6]
https://github.com/gemian/xkeyboard-config/blob/buster/symbols/planet_vndr/cosmo does not contain the "Swiss keyboard" Keymap that was sold with the Comso,

**Comment by adamboardman** [comment]
We entered initial versions of what we thought would be the most popular ones though its always best to have a native speaker to pick sensible fn+shift key values where there are no markings. In history you'll see we have some contributions from nafmo and szopin etc. I never asked planet for an official list of keyboards, I mostly used the images someone handily uploaded to the oesf.org forum as a source of what keys are where.

Would you like to contribute your map? Or do you want us to do it for you?

**Comment by sschueller** [comment]
Thanks for the quick reply. I will give it a shot, otherwise I will provide a photo. Thanks

**Comment by adamboardman** [comment]
If your feeling above and beyond you could also update the wiki with the extra keys you pick: [KeyboardMappings](https://github.com/gemian/gemian/wiki/KeyboardMappings)

**Comment by adamboardman** [comment]
Thanks, I don't think there is anything you can do about the now missing F* keys, I agree printed on functions should take precedence.
