### ISSUE TITLE
Japanese keyboard layout is wrong in planet_vndr/cosmo, planet_vndr/gemini

### ISSUE THREAD

**Issue by midorism64** [gemian/xkeyboard-config#9]
In Cosmo and Gemini's Japanese keyboard, Fn + Y / Fn + Kana_N(ん) is slash.
https://planetcom.squarespace.com/device

However, it's defined as a backslash in planet_vndr/cosmo and planet_vndr/gemini.

**Comment by adamboardman** [comment]
Thanks for letting us know.
